import {
    faSignOutAlt,
    faCoins,
    faTags,
    faTicketAlt,
    faUsers,
    faRocket,
    faListAlt,
    faCogs,
    faHandsHelping
  } from '@fortawesome/free-solid-svg-icons'
  import {
    Speed,
    PeopleAlt,
    CreditCard,
    RequestPage,
    EventNote,
    MoveUp,
  } from "@mui/icons-material";
  import Colors from './Colors'
  import Config from '../config.js'
  const helper = {
    company: 'USC',
    APP_NAME: 'USC-ERDT:IMS',
    APP_NAME_BASIC: 'ERDT-IMS',
    APP_EMAIL: '',
    APP_WEBSITE: '',
    APP_HOST: 'com.jiph',
    ACCOUNT_TYPE: 'staff',
    accountTypes: ['admin', 'staff', 'scholar', 'applicant', ],
    ledgerAllowed: ['admin', 'staff'],
    OTHER_HOST: Config.OTHER_HOST,
    loginMenu: [],
    menu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      {
        title: "Compliance",
        icon: MoveUp,
        route: '/compliance',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: [
          {
            title: 'Limits',
            icon: MoveUp,
            route: '/transaction_limits',
            color: null,
            iconType: 'material',
            isShow: true,
            active: false,
            subMenu: []
          }
        ]
      },
      {
        title: "Customer Service",
        icon: faTicketAlt,
        route: '/customer_services',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome',
        subMenu: [{
          title: "Tickets",
          icon: faTicketAlt,
          route: '/tickets',
          color: null,
          isShow: true,
          active: false,
          iconType: 'fontawesome',
        }]
      },
      // {
      //   title: 'Partners',
      //   icon: faUsers,
      //   route: '/partners',
      //   color: null,
      //   iconType: 'fontawesome',
      //   isShow: true,
      //   active: false,
      //   subMenu: [{
      //     title: "Plans",
      //     icon: EventNote,
      //     route: '/plans',
      //     color: null,
      //     isShow: true,
      //     active: false,
      //     iconType: 'material',
      //     subMenu: []
      //   }, {
      //     title: 'Monitoring',
      //     icon: faCertificate,
      //     route: '/monitoring',
      //     color: null,
      //     isShow: true,
      //     iconType: 'fontawesome',
      //     active: false,
      //   }, {
      //     title: 'Community',
      //     icon: faUsers,
      //     route: '/community',
      //     color: null,
      //     isShow: true,
      //     iconType: 'fontawesome',
      //     active: false,
      //   }]
      // },
      {
        title: "Finance",
        icon: faCoins,
        route: '/finance',
        color: null,
        iconType: 'fontawesome',
        isShow: true,
        active: false,
        subMenu: [
          //   {
          //   title: 'Peer to Peer',
          //   icon: RequestPage,
          //   route: '/requests',
          //   color: null,
          //   isShow: true,
          //   iconType: 'material',
          //   active: false,
          // },
          {
            title: "Accounts",
            icon: PeopleAlt,
            route: '/accounts',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material',
            subMenu: [{
              title: "Registered",
              icon: PeopleAlt,
              route: '/accounts',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            }, 
            {
              title: "Preregistered",
              icon: PeopleAlt,
              route: '/preregister',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            }]
          },
          {
            title: 'Balance Inquiry',
            icon: RequestPage,
            route: '/balance_inquiry',
            color: null,
            isShow: true,
            iconType: 'material',
            active: false,
          },
          {
            title: "Cash In",
            icon: faCoins,
            route: '/dashboard',
            color: null,
            iconType: 'fontawesome',
            isShow: true,
            active: false,
            subMenu: [
              {
                title: "Funds in Clearing",
                icon: faCoins,
                route: '/funds_in_clearing',
                color: null,
                iconType: 'fontawesome',
                isShow: true,
                active: false,
                subMenu: []
              },
              {
                title: "Methods",
                icon: faCoins,
                route: '/cashins',
                color: null,
                iconType: 'fontawesome',
                isShow: true,
                active: false,
                subMenu: []
              }
            ]
          }, {
            title: "Cash Out",
            icon: faCoins,
            route: '/cash_outs',
            color: null,
            isShow: true,
            active: false,
            iconType: 'fontawesome',
            subMenu: [{
              title: "Methods",
              icon: faCoins,
              route: '/cashouts',
              color: null,
              iconType: 'fontawesome',
              isShow: true,
              active: false,
            }, {
              title: "Transactions",
              icon: faCoins,
              route: '/cashout_transactions',
              color: null,
              iconType: 'fontawesome',
              isShow: true,
              active: false,
            }]
          }, {
            title: 'Fees Comparison',
            icon: MoveUp,
            route: '/fees_comparison',
            color: null,
            iconType: 'material',
            isShow: true,
            active: false,
            subMenu: []
          }, {
            title: 'Forex Rates',
            icon: RequestPage,
            route: '/forex_rates',
            color: null,
            isShow: true,
            iconType: 'material',
            active: false,
          }, {
            title: 'Forex Transactions',
            icon: RequestPage,
            route: '/forex',
            color: null,
            isShow: true,
            iconType: 'material',
            active: false,
          }, {
            title: "Ledgers",
            icon: faCoins,
            route: '/ledgers',
            color: null,
            iconType: 'fontawesome',
            isShow: true,
            active: false,
          }, {
            title: 'Send Money',
            icon: RequestPage,
            route: '/send_money',
            color: null,
            isShow: true,
            iconType: 'material',
            active: false,
          },
         {
            title: "Send to wallets",
            icon: faCoins,
            route: '/send_to_wallets',
            color: null,
            iconType: 'fontawesome',
            isShow: true,
            active: false,
          }, {
            title: "S2RA Wallets",
            icon: CreditCard,
            route: '/s2ra_wallets',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material'
          },
          // {
          //   title: "Enable Support",
          //   icon: Engineering,
          //   route: '/requests/support',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material',
          // },
          {
            title: "Transfer Charges",
            icon: MoveUp,
            route: '/transfer_charges',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material'
          },
          // {
          //   title: "Delivery Fees",
          //   icon: AttachMoney,
          //   route: '/delivery_fees',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material'
          // },
          // {
          //   title: "Withdrawals",
          //   icon: CreditCard,
          //   route: '/withdrawals',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material'
          // },
          {
            title: 'Wallet Accounting',
            icon: CreditCard,
            route: '/wallet_accounting',
            color: null,
            iconType: 'material',
            isShow: true,
            active: false,
            subMenu: []
          }]
      },
      {
        title: "Human Resources",
        icon: faUsers,
        route: '/human_resources',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome',
        subMenu: [{
          title: "Schedules",
          icon: faListAlt,
          route: '/schedules',
          color: null,
          iconType: 'fontawesome',
          isShow: true,
          active: false,
        }]
      },
      {
        title: 'Marketing',
        icon: faRocket,
        route: '/marketing',
        color: null,
        isShow: true,
        iconType: 'fontawesome',
        active: false,
        subMenu: [
          // {
          //   title: 'Peer to Peer',
          //   icon: RequestPage,
          //   route: '/requests',
          //   color: null,
          //   isShow: true,
          //   iconType: 'material',
          //   active: false,
          // },
          {
            title: "Accounts",
            icon: PeopleAlt,
            route: '/accounts',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material',
            subMenu: [{
              title: "Registered",
              icon: PeopleAlt,
              route: '/accounts',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            },
            // {
            //   title: "Staff Accounts",
            //   icon: PeopleAlt,
            //   route: '/staff_accounts',
            //   color: null,
            //   iconType: 'material',
            //   isShow: true,
            //   active: false,
            // }, 
            {
              title: "Preregistered",
              icon: PeopleAlt,
              route: '/preregister',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            }]
          },
          // {
          //   title: "Plans",
          //   icon: EventNote,
          //   route: '/plans',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material',
          //   subMenu: []
          // },
          {
            title: "Campaigns",
            icon: faRocket,
            route: '/campaigns',
            color: null,
            isShow: true,
            active: false,
            iconType: 'fontawesome'
          }, {
            title: "Coupons",
            icon: faTags,
            route: '/coupons',
            color: null,
            isShow: true,
            active: false,
            iconType: 'fontawesome'
          }, {
            title: "Referrals",
            icon: EventNote,
            route: '/referrals',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material',
            subMenu: []
          }]
      },
      {
        title: 'Operations',
        icon: faListAlt,
        route: '/operations',
        color: null,
        isShow: true,
        iconType: 'fontawesome',
        active: false,
        subMenu: [
          // {
          //   title: 'Peer to Peer',
          //   icon: RequestPage,
          //   route: '/requests',
          //   color: null,
          //   isShow: true,
          //   iconType: 'material',
          //   active: false,
          // },
          {
            title: "Accounts",
            icon: PeopleAlt,
            route: '/accounts',
            color: null,
            isShow: true,
            active: false,
            iconType: 'material',
            subMenu: [{
              title: "Registered",
              icon: PeopleAlt,
              route: '/accounts',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            },
            // {
            //   title: "Staff Accounts",
            //   icon: PeopleAlt,
            //   route: '/staff_accounts',
            //   color: null,
            //   iconType: 'material',
            //   isShow: true,
            //   active: false,
            // },
            {
              title: "Preregistered",
              icon: PeopleAlt,
              route: '/preregister',
              color: null,
              iconType: 'material',
              isShow: true,
              active: false,
            }]
          },
          // {
          //   title: "Plans",
          //   icon: EventNote,
          //   route: '/plans',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material',
          //   subMenu: []
          // },
          // {
          //   title: "Scopes",
          //   icon: LocationOn,
          //   route: '/scopes',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material',
          //   subMenu: []
          // }
        ]
      },
      {
        title: "System Admin",
        icon: faCogs,
        route: '/system_admin',
        color: null,
        iconType: 'fontawesome',
        isShow: true,
        active: false,
        subMenu: [{
          title: "Registered",
          icon: PeopleAlt,
          route: '/accounts',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }, {
          title: "Preregistered",
          icon: PeopleAlt,
          route: '/preregister',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }, {
          title: "Staff Accounts",
          icon: PeopleAlt,
          route: '/staff_accounts',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }, {
          title: "Services",
          icon: faHandsHelping,
          route: '/services',
          color: null,
          isShow: true,
          active: false,
          iconType: 'fontawesome',
          subMenu: []
        }]
      },
      // {
      //   title: "Settings",
      //   icon: faCog,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'fontawesome',
      //   subMenu: []
      // },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger
      }],
    financeMenu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      {
        title: "Accounts",
        icon: PeopleAlt,
        route: '/accounts',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material',
        subMenu: [{
          title: "Registered",
          icon: PeopleAlt,
          route: '/accounts',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        },
        {
          title: "Preregistered",
          icon: PeopleAlt,
          route: '/preregister',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }]
      },
      {
        title: 'Balance Inquiry',
        icon: RequestPage,
        route: '/balance_inquiry',
        color: null,
        isShow: true,
        iconType: 'material',
        active: false,
      },
      {
        title: "Cash In",
        icon: faCoins,
        route: '/dashboard',
        color: null,
        iconType: 'fontawesome',
        isShow: true,
        active: false,
        subMenu: [{
          title: "Funds in Clearing",
          icon: faCoins,
          route: '/funds_in_clearing',
          color: null,
          iconType: 'fontawesome',
          isShow: true,
          active: false,
          subMenu: []
        }, {
            title: "Methods",
            icon: faCoins,
            route: '/cashins',
            color: null,
            iconType: 'fontawesome',
            isShow: true,
            active: false,
            subMenu: []
          }]
      }, {
        title: "Cash Out",
        icon: faCoins,
        route: '/cash_outs',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome',
        subMenu: [{
          title: "Methods",
          icon: faCoins,
          route: '/cashouts',
          color: null,
          iconType: 'fontawesome',
          isShow: true,
          active: false,
        }, {
          title: "Transactions",
          icon: faCoins,
          route: '/cashout_transactions',
          color: null,
          iconType: 'fontawesome',
          isShow: true,
          active: false,
        }]
      }, {
        title: "Charges",
        icon: MoveUp,
        route: '/transfer_charges',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material',
        subMenu: [{
          title: "Transfer Charges",
          icon: MoveUp,
          route: '/transfer_charges',
          color: null,
          isShow: true,
          active: false,
          iconType: 'material'
        },
          // {
          //   title: "Delivery Fees",
          //   icon: AttachMoney,
          //   route: '/delivery_fees',
          //   color: null,
          //   isShow: true,
          //   active: false,
          //   iconType: 'material',
          //   subMenu: []
          // }
        ]
      },
      // {
      //   title: "Peer to Peer",
      //   icon: faCoins,
      //   route: '/requests',
      //   color: null,
      //   iconType: 'fontawesome',
      //   isShow: true,
      //   active: false,
      //   subMenu: []
      // },
      {
        title: 'Fees Comparison',
        icon: MoveUp,
        route: '/fees_comparison',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      {
        title: 'Forex',
        icon: RequestPage,
        route: '/forex',
        color: null,
        isShow: true,
        iconType: 'material',
        active: false,
        subMenu: [{
          title: 'Rates',
          icon: RequestPage,
          route: '/forex_rates',
          color: null,
          isShow: true,
          iconType: 'material',
          active: false,
        }, {
          title: 'Transactions',
          icon: RequestPage,
          route: '/forex',
          color: null,
          isShow: true,
          iconType: 'material',
          active: false,
        }]
      }, 
      {
        title: "Ledgers",
        icon: faCoins,
        route: '/ledgers',
        color: null,
        iconType: 'fontawesome',
        isShow: true,
        active: false,
        subMenu: []
      }, 
      {
        title: 'Send Money',
        icon: RequestPage,
        route: '/send_money',
        color: null,
        isShow: true,
        iconType: 'material',
        active: false,
      },
      // {
      //   title: 'Plus Minus',
      //   icon: RequestPage,
      //   route: '/plus_minus',
      //   color: null,
      //   isShow: true,
      //   iconType: 'material',
      //   active: false,
      // },
      {
        title: "Send to wallets",
        icon: faCoins,
        route: '/send_to_wallets',
        color: null,
        iconType: 'fontawesome',
        isShow: true,
        active: false,
      },
      // {
      //   title: "Enable Support",
      //   icon: Engineering,
      //   route: '/requests/support',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      // {
      //   title: "Withdrawals",
      //   icon: CreditCard,
      //   route: '/withdrawals',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   subMenu: [],
      //   iconType: 'material'
      // },
      {
        title: "S2RA Wallets",
        icon: CreditCard,
        route: '/s2ra_wallets',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material'
      },
      // {
      //   title: "Settings",
      //   icon: Engineering,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: 'Wallet Accounting',
        icon: CreditCard,
        route: '/wallet_accounting',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger
      }],
    complianceMenu: [
      {
        title: 'Limits',
        icon: MoveUp,
        route: '/transaction_limits',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      }
    ],
    operationMenu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      // {
      //   title: 'Peer to Peer',
      //   icon: RequestPage,
      //   route: '/requests',
      //   color: null,
      //   isShow: true,
      //   iconType: 'material',
      //   active: false,
      //   subMenu: []
      // },
      {
        title: "Accounts",
        icon: PeopleAlt,
        route: '/accounts',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material',
        subMenu: [{
          title: "Registered",
          icon: PeopleAlt,
          route: '/accounts',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        },
        // {
        //   title: "Staff Accounts",
        //   icon: PeopleAlt,
        //   route: '/staff_accounts',
        //   color: null,
        //   iconType: 'material',
        //   isShow: true,
        //   active: false,
        // },
        {
          title: "Preregistered",
          icon: PeopleAlt,
          route: '/preregister',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }]
      },
      // {
      //   title: "Plans",
      //   icon: EventNote,
      //   route: '/plans',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      // {
      //   title: "Scopes",
      //   icon: LocationOn,
      //   route: '/scopes',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      // {
      //   title: "Settings",
      //   icon: Engineering,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger,
        subMenu: []
      }],
    marketingMenu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      // {
      //   title: 'Peer to Peer',
      //   icon: RequestPage,
      //   route: '/requests',
      //   color: null,
      //   isShow: true,
      //   iconType: 'material',
      //   active: false,
      //   subMenu: []
      // },
      {
        title: "Accounts",
        icon: PeopleAlt,
        route: '/accounts',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material',
        subMenu: [{
          title: "Registered",
          icon: PeopleAlt,
          route: '/accounts',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        },
        // {
        //   title: "Staff Accounts",
        //   icon: PeopleAlt,
        //   route: '/staff_accounts',
        //   color: null,
        //   iconType: 'material',
        //   isShow: true,
        //   active: false,
        // },
        {
          title: "Preregistered",
          icon: PeopleAlt,
          route: '/preregister',
          color: null,
          iconType: 'material',
          isShow: true,
          active: false,
        }]
      },
      // {
      //   title: "Plans",
      //   icon: EventNote,
      //   route: '/plans',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: "Campaigns",
        icon: faRocket,
        route: '/campaigns',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome'
      },
      {
        title: "Coupons",
        icon: faTags,
        route: '/coupons',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome',
        subMenu: []
      },
      // {
      //   title: "Settings",
      //   icon: Engineering,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: "Referrals",
        icon: EventNote,
        route: '/referrals',
        color: null,
        isShow: true,
        active: false,
        iconType: 'material',
        subMenu: []
      },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger
      }],
    supportMenu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      }, {
        title: "Tickets",
        icon: faTicketAlt,
        route: '/tickets',
        color: null,
        isShow: true,
        active: false,
        iconType: 'fontawesome',
        subMenu: []
      },
      // {
      //   title: "Settings",
      //   icon: Engineering,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger
      }],
    businessMenu: [
      {
        title: 'Dashboard',
        icon: Speed,
        route: '/dashboard',
        color: null,
        iconType: 'material',
        isShow: true,
        active: false,
        subMenu: []
      },
      // {
      //   title: "Plans",
      //   icon: EventNote,
      //   route: '/plans',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      // {
      //   title: 'Monitoring',
      //   icon: faCertificate,
      //   route: '/monitoring',
      //   color: null,
      //   isShow: true,
      //   iconType: 'fontawesome',
      //   active: false,
      //   subMenu: []
      // },
      // {
      //   title: 'Community',
      //   icon: faUsers,
      //   route: '/community',
      //   color: null,
      //   isShow: true,
      //   iconType: 'fontawesome',
      //   active: false,
      //   subMenu: []
      // },
      // {
      //   title: "Settings",
      //   icon: Engineering,
      //   route: '/settings',
      //   color: null,
      //   isShow: true,
      //   active: false,
      //   iconType: 'material',
      //   subMenu: []
      // },
      {
        title: 'Logout',
        icon: faSignOutAlt,
        route: '/logout',
        isShow: true,
        iconType: 'fontawesome',
        color: Colors.danger
      }
    ]
  }
  export default helper;