export default{
	authenticate: 'authenticate/auth',
	authenticatedUser: 'authenticate/user',
	// accountCreate: 'accounts/create',
	// accountDelete: 'accounts/delete',
	// accountRetrieve: 'accounts/retrieve',
	// accountUpdate: 'accounts/update',
	// accountUpdateType: 'accounts/update_account_type',
	// accountUpdateStatus: 'accounts/update_verification',
	// accountRequestChangePassword: 'accounts/request_change_password',
	// categoriesCreate: 'categories/create',
	// categoriesRetrieve: 'categories/retrieve',
	// categoriesDelete: 'categories/delete',
	// categoriesUpdate: 'categories/update',
	// payloadsRetrieve: 'payloads/retrieve',
	// payloadsRetrieveWithDecode: 'payloads/retrieve_with_decode',
	// payloadsCreateWithLimit: 'payloads/create_with_limit',
	// payloadsCreate: 'payloads/create',
	// payloadsUpdate: 'payloads/update',
	// payloadsUpdateData: 'payloads/update_data',
	// jobRetrieveSummary: 'jobs/retrieve_summary',
	// reportRetrieve: 'job_payments/retrieve_summary_admin',
	// reportDelete: 'job_payments/delete',
	// jobRetrieve: 'jobs/retrieve',
	// messengerGroupRetrieve: 'messenger_groups/retrieve',
	// messagesRetrieve: 'messenger_messages/retrieve',
	// messagesCreate: 'messenger_messages/create',
	// candidatesRetrieve: 'candidates/retrieve',
	// contractRetrieveJobSummary: 'contracts/retrieve_job_summary',
	// contractRetrieveSummary: 'contracts/retrieve_summary',
	// contractUpdate: 'contracts/update',
	// candidateRetrieveMatching: 'candidates/retrieve_matching',
	// candidateRetrieve: 'candidates/retrieve',
}